# This is the OpenAPI specification for your service. It is used to generate the client code.
# To generate the server code, use the Gradle task `openApiGenerate`. The 
# generated code will be placed in `build/generate-resources/main`.
#
# We will evaluate you based on how well you design your API.
# 1. How well it follows REST principles.
# 2. How easy it is to understand and use.
#
# References
# 1. https://swagger.io/specification/
openapi: "3.0.0"
info:
  version: 1.0.0
  title: User Service
  license:
    name: MIT
servers:
  - url: http://localhost
paths:
  /register:
    post:
      summary: register
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
      responses:
        '200':
          description: Success Register User
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/RegisterUserResponse"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
components:
  schemas:
    RegisterUserRequest:
      type: object
      required:
        - name
        - phone
        - password
      properties:
        name: 
          type: string
        phone:
          type: string
        password: 
          type: string

    RegisterUserResponse:
      type: object
      required:
        - id
      properties:
        id: 
          type: string
        phone:
          type: string
        password: 
          type: string

    ErrorMessage:
      type: object
      required:
        - message
      properties:
        message:
          type: string
